# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = Category.create(
    [
        {name: "sneakers" },
        {name: "boots" },
        {name: "clogs" },
        {name: "flats" },
        {name: "heels" },
        {name: "loafers" }
    ]
)

users = User.create(
    [
         {
  id: 22,
  title: nil,
  subtitle: "Test",
  creator_id: 2,
  category_id: 1,
  subcategory_id: nil,
  description: nil,
  risks: nil,
  faqs: nil,
  length: nil,
  amount_received: nil,
  goal: nil,
  launched?: false,
  location: "Belgium"},
 {
  id: 23,
  title: nil,
  subtitle: "Test",
  creator_id: 2,
  category_id: 1,
  subcategory_id: nil,
  description: nil,
  risks: nil,
  faqs: nil,
  length: nil,
  amount_received: nil,
  goal: nil,
  launched?: false,
  location: "Belgium"},
 {
  id: 25,
  title: "Shoes",
  subtitle: "Another Test",
  creator_id: 2,
  category_id: 4,
  subcategory_id: nil,
  description: "",
  risks: "",
  faqs: "",
  length: nil,
  amount_received: nil,
  goal: nil,
  created_at: Wed, 05 Jun 2019 20:07:31 UTC +00:00,
  launched?: false,
  location: "france"},

    ]
)


projects {
    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Australia",
    },

    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Australia",
    },

    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Denmark",
    },



    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Denmark",
    },

    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Denmark",
    },

    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 4,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Canada",
    },

    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 4,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Canada",
    },

    { title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Canada",
    },

    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Canada",
    },
    
    { title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    } ,
    
    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    },
    
    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Japan",
    },
    
    {  title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Hong Kong",
    },
    
    {  title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "France",
    },
    
    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "australia",
    },

    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "australia",
    },


    {title: nil,
    subtitle: "test",
    creator_id: 2,
    category_id: 2,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "boots",
    },


    {title: nil,
    subtitle: "test13",
    creator_id: 2,
    category_id: 3,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "canada",
    },

    {title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",},



    {title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    },

    {title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    },

    { title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    },
    
    {title: nil,
    subtitle: "Test",
    creator_id: 2,
    category_id: 1,
    subcategory_id: nil,
    description: nil,
    risks: nil,
    faqs: nil,
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "Belgium",
    },


    
    {title: "Shoes",
    subtitle: "Another Test",
    creator_id: 2,
    category_id: 4,
    subcategory_id: nil,
    description: "",
    risks: "",
    faqs: "",
    length: nil,
    amount_received: nil,
    goal: nil,
    launched?: false,
    location: "france",}


    ]
)